/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import controlador.ControladorInicio;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author pedro
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        ControladorInicio.iniciarSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUser = new javax.swing.JPanel();
        txtUsuarioID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuarioNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUsuarioEstado = new javax.swing.JTextArea();
        txtUsuarioContraseña = new javax.swing.JTextField();
        btUsuarioGuardar = new javax.swing.JButton();
        btUsuarioEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtUsuarioFoto = new javax.swing.JTextField();
        panelArma = new javax.swing.JPanel();
        txtArmaID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtArmaNombre = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtArmaCaracteristicas = new javax.swing.JTextArea();
        txtArmaAtaque = new javax.swing.JTextField();
        btArmaGuardar = new javax.swing.JButton();
        btArmaEliminar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtArmaFoto = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtArmaDaño = new javax.swing.JTextField();
        checkArmaArrojadiza = new javax.swing.JCheckBox();
        cbArmaCar = new javax.swing.JComboBox<>();
        cbArmaTipo = new javax.swing.JComboBox<>();
        panelPersonaje = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtPersonajeNombre = new javax.swing.JTextField();
        btPersonajeGuardar = new javax.swing.JButton();
        btPersonajeEliminar = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        txtPersonajeFoto = new javax.swing.JTextField();
        txtPersonajeFuerza = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        cbPersonajeUser = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtPersonajeDestreza = new javax.swing.JTextField();
        txtPersonajeConstitucion = new javax.swing.JTextField();
        txtPersonajeInteligencia = new javax.swing.JTextField();
        txtPersonajeSabiduria = new javax.swing.JTextField();
        txtPersonajeCarisma = new javax.swing.JTextField();
        panelVistas = new javax.swing.JPanel();
        btVistaUsers = new javax.swing.JButton();
        btVistaCampañas = new javax.swing.JButton();
        btVistaPersonajes = new javax.swing.JButton();
        btVistaArmas = new javax.swing.JButton();
        btVistaArmasPer = new javax.swing.JButton();
        panelArmaPersonaje = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtArmaPerBonificador = new javax.swing.JTextField();
        btArmaPerGuardar = new javax.swing.JButton();
        btArmaPerEliminar = new javax.swing.JButton();
        txtArmaPerCompetencia = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        cbArmaPerUsuario = new javax.swing.JComboBox<>();
        cbArmaPerCampaña = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        cbArmaPerArma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        panelUser.setToolTipText("");

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Estado");

        txtUsuarioEstado.setColumns(20);
        txtUsuarioEstado.setRows(5);
        jScrollPane1.setViewportView(txtUsuarioEstado);

        btUsuarioGuardar.setText("Guardar");
        btUsuarioGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioGuardarActionPerformed(evt);
            }
        });

        btUsuarioEliminar.setText("Eliminar");
        btUsuarioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioEliminarActionPerformed(evt);
            }
        });

        jLabel5.setText("Foto");

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btUsuarioGuardar)
                .addGap(74, 74, 74)
                .addComponent(btUsuarioEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUserLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUserLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUserLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUserLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelUserLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        panelUserLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtUsuarioContraseña, txtUsuarioFoto, txtUsuarioID, txtUsuarioNombre});

        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuarioContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsuarioFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUsuarioGuardar)
                    .addComponent(btUsuarioEliminar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelArma.setBorder(javax.swing.BorderFactory.createTitledBorder("Arma"));
        panelArma.setToolTipText("");

        jLabel22.setText("ID");

        jLabel23.setText("Nombre");

        jLabel24.setText("Ataque");

        jLabel25.setText("Daño");

        txtArmaCaracteristicas.setColumns(20);
        txtArmaCaracteristicas.setRows(5);
        jScrollPane6.setViewportView(txtArmaCaracteristicas);

        btArmaGuardar.setText("Guardar");
        btArmaGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArmaGuardarActionPerformed(evt);
            }
        });

        btArmaEliminar.setText("Eliminar");
        btArmaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArmaEliminarActionPerformed(evt);
            }
        });

        jLabel26.setText("Foto");

        jLabel27.setText("Tipo");

        jLabel28.setText("Arrojadiza");

        jLabel29.setText("Caracteristica");

        jLabel30.setText("Caracteristicas");

        cbArmaCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuerza", "Destreza", "Constitucion", "Inteligencia", "Sabiduria", "Carisma" }));

        cbArmaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelArmaLayout = new javax.swing.GroupLayout(panelArma);
        panelArma.setLayout(panelArmaLayout);
        panelArmaLayout.setHorizontalGroup(
            panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArmaLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArmaID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArmaLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArmaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArmaLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArmaAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArmaLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkArmaArrojadiza, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArmaLayout.createSequentialGroup()
                        .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArmaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbArmaCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelArmaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btArmaGuardar)
                        .addGap(61, 61, 61)
                        .addComponent(btArmaEliminar))
                    .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelArmaLayout.createSequentialGroup()
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbArmaTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelArmaLayout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtArmaDaño, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelArmaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel22, jLabel23, jLabel24, jLabel25, jLabel26, jLabel27, jLabel28, jLabel29, jLabel30});

        panelArmaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbArmaCar, checkArmaArrojadiza, txtArmaAtaque, txtArmaDaño, txtArmaFoto, txtArmaID, txtArmaNombre});

        panelArmaLayout.setVerticalGroup(
            panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArmaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArmaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtArmaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtArmaAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtArmaDaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cbArmaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(checkArmaArrojadiza))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cbArmaCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArmaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btArmaGuardar)
                    .addComponent(btArmaEliminar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelPersonaje.setBorder(javax.swing.BorderFactory.createTitledBorder("Personaje"));
        panelPersonaje.setToolTipText("");

        jLabel31.setText("Usuario");

        jLabel32.setText("Nombre");

        jLabel34.setText("Fuerza");

        btPersonajeGuardar.setText("Guardar");
        btPersonajeGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPersonajeGuardarActionPerformed(evt);
            }
        });

        btPersonajeEliminar.setText("Eliminar");
        btPersonajeEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPersonajeEliminarActionPerformed(evt);
            }
        });

        jLabel35.setText("Foto");

        cbPersonajeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel41.setText("Destreza");

        jLabel42.setText("Constitucion");

        jLabel33.setText("Inteligencia");

        jLabel36.setText("Sabiduria");

        jLabel37.setText("Carisma");

        txtPersonajeCarisma.setToolTipText("");

        javax.swing.GroupLayout panelPersonajeLayout = new javax.swing.GroupLayout(panelPersonaje);
        panelPersonaje.setLayout(panelPersonajeLayout);
        panelPersonajeLayout.setHorizontalGroup(
            panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonajeLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPersonajeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonajeLayout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPersonajeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPersonajeLayout.createSequentialGroup()
                        .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPersonajeCarisma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPersonajeSabiduria, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPersonajeInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPersonajeConstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPersonajeDestreza, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPersonajeFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPersonajeLayout.createSequentialGroup()
                        .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPersonajeGuardar)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPersonajeFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPersonajeEliminar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPersonajeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel31, jLabel32, jLabel33, jLabel34, jLabel35, jLabel36, jLabel37, jLabel40, jLabel41, jLabel42});

        panelPersonajeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbPersonajeUser, txtPersonajeCarisma, txtPersonajeConstitucion, txtPersonajeDestreza, txtPersonajeFoto, txtPersonajeFuerza, txtPersonajeInteligencia, txtPersonajeNombre, txtPersonajeSabiduria});

        panelPersonajeLayout.setVerticalGroup(
            panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonajeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cbPersonajeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtPersonajeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtPersonajeFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtPersonajeDestreza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtPersonajeConstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtPersonajeInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtPersonajeSabiduria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtPersonajeCarisma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtPersonajeFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPersonajeGuardar)
                    .addComponent(btPersonajeEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVistas.setBorder(javax.swing.BorderFactory.createTitledBorder("Vistas todos"));

        btVistaUsers.setText("Usuarios");
        btVistaUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVistaUsersActionPerformed(evt);
            }
        });

        btVistaCampañas.setText("Campañas");
        btVistaCampañas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVistaCampañasActionPerformed(evt);
            }
        });

        btVistaPersonajes.setText("Personajes");
        btVistaPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVistaPersonajesActionPerformed(evt);
            }
        });

        btVistaArmas.setText("Armas");
        btVistaArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVistaArmasActionPerformed(evt);
            }
        });

        btVistaArmasPer.setText("Armas_Personajes");
        btVistaArmasPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVistaArmasPerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVistasLayout = new javax.swing.GroupLayout(panelVistas);
        panelVistas.setLayout(panelVistasLayout);
        panelVistasLayout.setHorizontalGroup(
            panelVistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistasLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelVistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVistaCampañas)
                    .addComponent(btVistaUsers)
                    .addComponent(btVistaPersonajes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(panelVistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVistaArmas)
                    .addComponent(btVistaArmasPer))
                .addGap(43, 43, 43))
        );

        panelVistasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btVistaArmas, btVistaArmasPer, btVistaCampañas, btVistaPersonajes, btVistaUsers});

        panelVistasLayout.setVerticalGroup(
            panelVistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistasLayout.createSequentialGroup()
                .addGroup(panelVistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVistasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btVistaUsers)
                        .addGap(18, 18, 18)
                        .addComponent(btVistaCampañas)
                        .addGap(18, 18, 18)
                        .addComponent(btVistaPersonajes))
                    .addGroup(panelVistasLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btVistaArmas)
                        .addGap(18, 18, 18)
                        .addComponent(btVistaArmasPer)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        panelArmaPersonaje.setBorder(javax.swing.BorderFactory.createTitledBorder("Arma Personaje"));
        panelArmaPersonaje.setToolTipText("");

        jLabel38.setText("Usuario");

        jLabel39.setText("Bonificador Adicional");

        jLabel43.setText("Competencia");

        btArmaPerGuardar.setText("Guardar");
        btArmaPerGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArmaPerGuardarActionPerformed(evt);
            }
        });

        btArmaPerEliminar.setText("Eliminar");
        btArmaPerEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArmaPerEliminarActionPerformed(evt);
            }
        });

        jLabel45.setText("Campaña");

        cbArmaPerUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbArmaPerCampaña.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel51.setText("Arma");

        cbArmaPerArma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelArmaPersonajeLayout = new javax.swing.GroupLayout(panelArmaPersonaje);
        panelArmaPersonaje.setLayout(panelArmaPersonajeLayout);
        panelArmaPersonajeLayout.setHorizontalGroup(
            panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                        .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtArmaPerCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbArmaPerArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArmaPerBonificador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbArmaPerCampaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbArmaPerUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btArmaPerGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btArmaPerEliminar)
                        .addGap(36, 36, 36))))
        );

        panelArmaPersonajeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel38, jLabel39, jLabel43, jLabel45, jLabel51});

        panelArmaPersonajeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbArmaPerArma, cbArmaPerCampaña, cbArmaPerUsuario, txtArmaPerBonificador, txtArmaPerCompetencia});

        panelArmaPersonajeLayout.setVerticalGroup(
            panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArmaPersonajeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(cbArmaPerCampaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cbArmaPerUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(cbArmaPerArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtArmaPerBonificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtArmaPerCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addGap(18, 18, 18)
                .addGroup(panelArmaPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btArmaPerGuardar)
                    .addComponent(btArmaPerEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelVistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelArmaPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArmaPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelVistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btUsuarioGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUsuarioGuardarActionPerformed

    private void btUsuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUsuarioEliminarActionPerformed

    private void btPersonajeGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPersonajeGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPersonajeGuardarActionPerformed

    private void btPersonajeEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPersonajeEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPersonajeEliminarActionPerformed

    private void btArmaGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArmaGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btArmaGuardarActionPerformed

    private void btArmaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArmaEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btArmaEliminarActionPerformed

    private void btArmaPerGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArmaPerGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btArmaPerGuardarActionPerformed

    private void btArmaPerEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArmaPerEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btArmaPerEliminarActionPerformed

    private void btVistaUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVistaUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVistaUsersActionPerformed

    private void btVistaCampañasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVistaCampañasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVistaCampañasActionPerformed

    private void btVistaPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVistaPersonajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVistaPersonajesActionPerformed

    private void btVistaArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVistaArmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVistaArmasActionPerformed

    private void btVistaArmasPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVistaArmasPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVistaArmasPerActionPerformed

    public JComboBox<String> getCbArmaCar() {
        return cbArmaCar;
    }

    public JComboBox<String> getCbArmaPerArma() {
        return cbArmaPerArma;
    }

    public JComboBox<String> getCbArmaPerCampaña() {
        return cbArmaPerCampaña;
    }

    public JComboBox<String> getCbArmaPerUsuario() {
        return cbArmaPerUsuario;
    }

    public JComboBox<String> getCbArmaTipo() {
        return cbArmaTipo;
    }

    public void setCbArmaTipo(JComboBox<String> cbArmaTipo) {
        this.cbArmaTipo = cbArmaTipo;
    }

    public JComboBox<String> getCbPersonajeUser() {
        return cbPersonajeUser;
    }

    public JCheckBox getCheckArmaArrojadiza() {
        return checkArmaArrojadiza;
    }


    public JTextField getTxtArmaAtaque() {
        return txtArmaAtaque;
    }

    public JTextArea getTxtArmaCaracteristicas() {
        return txtArmaCaracteristicas;
    }

    public JTextField getTxtArmaDaño() {
        return txtArmaDaño;
    }

    public JTextField getTxtArmaFoto() {
        return txtArmaFoto;
    }

    public JTextField getTxtArmaID() {
        return txtArmaID;
    }

    public JTextField getTxtArmaNombre() {
        return txtArmaNombre;
    }

    public JTextField getTxtArmaPerBonificador() {
        return txtArmaPerBonificador;
    }

    public JTextField getTxtArmaPerCompetencia() {
        return txtArmaPerCompetencia;
    }

    public JTextField getTxtPersonajeCarisma() {
        return txtPersonajeCarisma;
    }

    public JTextField getTxtPersonajeConstitucion() {
        return txtPersonajeConstitucion;
    }

    public JTextField getTxtPersonajeDestreza() {
        return txtPersonajeDestreza;
    }

    public JTextField getTxtPersonajeFoto() {
        return txtPersonajeFoto;
    }

    public JTextField getTxtPersonajeFuerza() {
        return txtPersonajeFuerza;
    }

    public JTextField getTxtPersonajeInteligencia() {
        return txtPersonajeInteligencia;
    }

    public JTextField getTxtPersonajeNombre() {
        return txtPersonajeNombre;
    }

    public JTextField getTxtPersonajeSabiduria() {
        return txtPersonajeSabiduria;
    }

    public JTextField getTxtUsuarioContraseña() {
        return txtUsuarioContraseña;
    }

    public JTextArea getTxtUsuarioEstado() {
        return txtUsuarioEstado;
    }

    public JTextField getTxtUsuarioFoto() {
        return txtUsuarioFoto;
    }

    public JTextField getTxtUsuarioID() {
        return txtUsuarioID;
    }

    public JTextField getTxtUsuarioNombre() {
        return txtUsuarioNombre;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArmaEliminar;
    private javax.swing.JButton btArmaGuardar;
    private javax.swing.JButton btArmaPerEliminar;
    private javax.swing.JButton btArmaPerGuardar;
    private javax.swing.JButton btPersonajeEliminar;
    private javax.swing.JButton btPersonajeGuardar;
    private javax.swing.JButton btUsuarioEliminar;
    private javax.swing.JButton btUsuarioGuardar;
    private javax.swing.JButton btVistaArmas;
    private javax.swing.JButton btVistaArmasPer;
    private javax.swing.JButton btVistaCampañas;
    private javax.swing.JButton btVistaPersonajes;
    private javax.swing.JButton btVistaUsers;
    private javax.swing.JComboBox<String> cbArmaCar;
    private javax.swing.JComboBox<String> cbArmaPerArma;
    private javax.swing.JComboBox<String> cbArmaPerCampaña;
    private javax.swing.JComboBox<String> cbArmaPerUsuario;
    private javax.swing.JComboBox<String> cbArmaTipo;
    private javax.swing.JComboBox<String> cbPersonajeUser;
    private javax.swing.JCheckBox checkArmaArrojadiza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panelArma;
    private javax.swing.JPanel panelArmaPersonaje;
    private javax.swing.JPanel panelPersonaje;
    private javax.swing.JPanel panelUser;
    private javax.swing.JPanel panelVistas;
    private javax.swing.JTextField txtArmaAtaque;
    private javax.swing.JTextArea txtArmaCaracteristicas;
    private javax.swing.JTextField txtArmaDaño;
    private javax.swing.JTextField txtArmaFoto;
    private javax.swing.JTextField txtArmaID;
    private javax.swing.JTextField txtArmaNombre;
    private javax.swing.JTextField txtArmaPerBonificador;
    private javax.swing.JTextField txtArmaPerCompetencia;
    private javax.swing.JTextField txtPersonajeCarisma;
    private javax.swing.JTextField txtPersonajeConstitucion;
    private javax.swing.JTextField txtPersonajeDestreza;
    private javax.swing.JTextField txtPersonajeFoto;
    private javax.swing.JTextField txtPersonajeFuerza;
    private javax.swing.JTextField txtPersonajeInteligencia;
    private javax.swing.JTextField txtPersonajeNombre;
    private javax.swing.JTextField txtPersonajeSabiduria;
    private javax.swing.JTextField txtUsuarioContraseña;
    private javax.swing.JTextArea txtUsuarioEstado;
    private javax.swing.JTextField txtUsuarioFoto;
    private javax.swing.JTextField txtUsuarioID;
    private javax.swing.JTextField txtUsuarioNombre;
    // End of variables declaration//GEN-END:variables
}
