/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.ControladorArmaPersonaje;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.vo.Arma;
import modelo.vo.Personaje;

/**
 *
 * @author pedro
 */
public class vArmaPersonaje extends javax.swing.JDialog {

    /**
     * Creates new form vArmaPersonaje
     */
    public vArmaPersonaje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ControladorArmaPersonaje.iniciarSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbArmaPersonaje = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        cbArmaPerArma = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        txtArmaPerBonificador = new javax.swing.JTextField();
        btArmaPerGuardar = new javax.swing.JButton();
        btArmaPerEliminar = new javax.swing.JButton();
        cbArmaPerPersonaje = new javax.swing.JComboBox<>();
        btArmasPersonajes = new javax.swing.JButton();
        cbCompetencia = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtAtaque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbArmaPersonaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Personaje", "Arma", "Ataque", "Bonificador", "Competencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbArmaPersonaje);

        jLabel38.setText("Personaje");

        jLabel51.setText("Arma");

        jLabel39.setText("Bonificador Adicional");

        cbArmaPerArma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbArmaPerArmaItemStateChanged(evt);
            }
        });

        jLabel43.setText("Competencia");

        btArmaPerGuardar.setText("Guardar");
        btArmaPerGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArmaPerGuardarActionPerformed(evt);
            }
        });

        btArmaPerEliminar.setText("Eliminar");
        btArmaPerEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArmaPerEliminarActionPerformed(evt);
            }
        });

        cbArmaPerPersonaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbArmaPerPersonajeItemStateChanged(evt);
            }
        });

        btArmasPersonajes.setText("Ver todas");
        btArmasPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArmasPersonajesActionPerformed(evt);
            }
        });

        jLabel1.setText("Ataque total");

        txtAtaque.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btArmaPerGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btArmaPerEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btArmasPersonajes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbArmaPerArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbArmaPerPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArmaPerBonificador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel38, jLabel39, jLabel43, jLabel51});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbArmaPerArma, cbArmaPerPersonaje, cbCompetencia, txtArmaPerBonificador, txtAtaque});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cbArmaPerPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(cbArmaPerArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAtaque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtArmaPerBonificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(cbCompetencia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btArmaPerGuardar)
                    .addComponent(btArmaPerEliminar)
                    .addComponent(btArmasPersonajes))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbArmaPerArmaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbArmaPerArmaItemStateChanged
        // TODO add your handling code here:
        ControladorArmaPersonaje.cargarDatosArmaPersonaje();
    }//GEN-LAST:event_cbArmaPerArmaItemStateChanged

    private void btArmaPerGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArmaPerGuardarActionPerformed
        // TODO add your handling code here:
        ControladorArmaPersonaje.guardarArmaPersonaje();
        ControladorArmaPersonaje.cargarDatosArmaPersonaje();
    }//GEN-LAST:event_btArmaPerGuardarActionPerformed

    private void btArmaPerEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArmaPerEliminarActionPerformed
        // TODO add your handling code here:
        ControladorArmaPersonaje.borrarArmaPersonaje();
    }//GEN-LAST:event_btArmaPerEliminarActionPerformed

    private void cbArmaPerPersonajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbArmaPerPersonajeItemStateChanged
        // TODO add your handling code here:
        ControladorArmaPersonaje.cargarDatosArmaPersonaje();
    }//GEN-LAST:event_cbArmaPerPersonajeItemStateChanged

    private void btArmasPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArmasPersonajesActionPerformed
        // TODO add your handling code here:
        ControladorArmaPersonaje.mostrarArmasPersonajes();
    }//GEN-LAST:event_btArmasPersonajesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ControladorArmaPersonaje.cargarCb();
        ControladorArmaPersonaje.mostrarArmasPersonajes();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ControladorArmaPersonaje.cerrarSession();
    }//GEN-LAST:event_formWindowClosed

    public JComboBox<Arma> getCbArmaPerArma() {
        return cbArmaPerArma;
    }

    public JComboBox<Personaje> getCbArmaPerPersonaje() {
        return cbArmaPerPersonaje;
    }

    public JCheckBox getCbCompetencia() {
        return cbCompetencia;
    }

    public JTable getTbArmaPersonaje() {
        return tbArmaPersonaje;
    }

    public JTextField getTxtArmaPerBonificador() {
        return txtArmaPerBonificador;
    }

    public JLabel getTxtAtaque() {
        return txtAtaque;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArmaPerEliminar;
    private javax.swing.JButton btArmaPerGuardar;
    private javax.swing.JButton btArmasPersonajes;
    private javax.swing.JComboBox<Arma> cbArmaPerArma;
    private javax.swing.JComboBox<Personaje> cbArmaPerPersonaje;
    private javax.swing.JCheckBox cbCompetencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbArmaPersonaje;
    private javax.swing.JTextField txtArmaPerBonificador;
    private javax.swing.JLabel txtAtaque;
    // End of variables declaration//GEN-END:variables
}
